### PR TITLE
refactor: deduplicate palette colors

### PR DESCRIPTION
**Pull request by Skagoo**
This refactor takes care of color hex code duplication between `_catppuccin.scss` and `_<flavour>.scss`.

Specific flavours get their palette from `_catppuccin.scss` and use this to create their color variables.

Feedback is welcome, happy to revisit if required! 🐱

### CODE REVIEW

**Comment by nekowinston** [comment]
Thanks for your PR!

The original idea was to have the flavour files separately, in case people only needed one/a specific set of flavours.
I can see what you're doing, but I guess [the documentation](https://github.com/catppuccin/palette/tree/main/scss#import-one-by-one) would have to be updated, telling people to include e.g. `_catppuccin.scss` AND `_frappe.scss` in their project.

**Comment by Skagoo** [comment]
Ok, that's indeed an obvious overhead I missed. Not sure if it is even worth solving it like this then.

**Comment by nekowinston** [comment]
Yeah, requiring people to use two files for what's supposed to be the more minimalist usage is pretty counter-intuitive.

I'd happily accept changes to the PR generating those SCSS files, or might do it myself. De-duplicating where possible is always welcome. 🙂

**Review by nekowinston — CHANGES_REQUESTED** [review]
Just marking this as reviewed, see my [PR comment](https://github.com/catppuccin/palette/pull/39#issuecomment-1397098685).

**Comment by Skagoo** [comment]
Okay so a generator that spits out the scss palettes would be cool? I'll edit the PR somewhere this weekend.

**Comment by nekowinston** [comment]
Yeah, if possible similarly to #36, which changed our [generator scripts](https://github.com/catppuccin/palette/pull/36/files)

**Comment by Skagoo** [comment]
Okay, would like the different color formats as well?

**Comment by nekowinston** [comment]
I don't think it's needed since the Sass preprocessor offers the functions to change opacity, darken/lighten, regardless of the color format.

If I'm wrongly informed on that, and there would be some benefit, then probably yes.

**Pull request closed without merging**
