### PR TITLE
feat: lookup tables (hald-clut)

### PR DESCRIPTION
**Pull request by ozwaldorf**
# What 

Adds pregenerated hald-clut lookup tables and a script to regenerate them as needed.

Includes 4 noise variants and the (unofficial) oled flavor.

# Example

image

### CODE REVIEW

**Comment by backwardspy** [comment]
blocking this pending #49 as the work there will impact how we include LUTs.

**Comment by Gingeh** [comment]
I don't think we should be using a rust script for this. It's a glorified shell script that unnecessarily builds palette images identical to those [already in this repository](https://github.com/catppuccin/palette/tree/main/png) and then calls a shell command.

**Comment by backwardspy** [comment]
> I don't think we should be using a rust script for this. It's a glorified shell script that unnecessarily builds palette images identical to those [already in this repository](https://github.com/catppuccin/palette/tree/main/png) and then calls a shell command.

winston mentioned the possibility of generating LUTs (along with everything else in the repo) with node via imagemagick-wasm.

**Comment by ozwaldorf** [comment]
Rebased onto #49 and replaced stuff with nodejs. Png is reused

Still requires imagemagick to be installed on the system, but I'll tinker a bit with magick-wasm

Once 49 is merged I'll rebase again, but open for review in the meantime

**Comment by ozwaldorf** [comment]
Update:
I don't think it's a good idea to use magick-wasm. Wasm is limited to single thread execution and the library doesn't handle parallelism for `MagickImageCollection` evaluations, so it's extremely slow compared to the multithreaded binary. We need to duplicate the wasm instance 512 times and actually run multiple parallel operations on all of the instances to generate the LUT in any short amount of time

**Comment by ozwaldorf** [comment]
Closing due to inactivity, as well as both imagemagick/wasm not being ideal for this task. Also, other tools like [lutgen](https://github.com/ozwaldorf/lutgen-rs) are doing it better and faster now

**Pull request closed without merging**
